"""Add Invitation model

Revision ID: 0e9564129d1d
Revises: 1c6516c429bd
Create Date: 2025-03-27 09:14:49.197276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0e9564129d1d'
down_revision = '1c6516c429bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('email_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_code'), 'invitation', ['code'], unique=False)
    op.create_index(op.f('ix_invitation_email_to'), 'invitation', ['email_to'], unique=False)
    op.create_index(op.f('ix_invitation_id'), 'invitation', ['id'], unique=False)
    op.create_index(op.f('ix_invitation_inviter_id'), 'invitation', ['inviter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_inviter_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_email_to'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_code'), table_name='invitation')
    op.drop_table('invitation')
    # ### end Alembic commands ###
