"""Add OTP table for email verification

Revision ID: 1c6516c429bd
Revises: d85c9cd00dc5
Create Date: 2025-03-15 18:49:02.847437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c6516c429bd'
down_revision = 'd85c9cd00dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_verified column with a default value of False for existing records
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), server_default='False', nullable=False))
    
    # Create the OTP table
    op.create_table('otp',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('code', sa.String(length=6), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), server_default='False', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.drop_table('otp')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
