"""add_anonymous_user_support

Revision ID: 49cae7de98a4
Revises: e29e1eae0a90
Create Date: 2025-05-30 18:37:53.564465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '49cae7de98a4'
down_revision = 'e29e1eae0a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add default_anonymous_credit column with default value for existing records
    op.add_column('application', sa.Column('default_anonymous_credit', sa.Integer(), nullable=False, server_default='3'))
    # Remove the server_default constraint after adding the column
    op.alter_column('application', 'default_anonymous_credit', server_default=None)
    
    # Add is_anonymous column with default value for existing records
    op.add_column('user', sa.Column('is_anonymous', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Remove the server_default constraint after adding the column
    op.alter_column('user', 'is_anonymous', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_anonymous')
    op.drop_column('application', 'default_anonymous_credit')
    # ### end Alembic commands ###
