"""Add column credit to UserBase model

Revision ID: 676b7ec88021
Revises: 1a31ce608336
Create Date: 2024-09-07 13:55:11.878737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '676b7ec88021'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credit', sa.Integer(), nullable=True))
    user = sa.table('user', sa.column('credit'))
    op.execute(user.update().values(credit=3))
    op.alter_column('user', 'credit', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credit')
    # ### end Alembic commands ###
