"""Add redeem table

Revision ID: b12ce92d13ef
Revises: a609855f7789
Create Date: 2024-12-22 12:48:35.215985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b12ce92d13ef'
down_revision = 'a609855f7789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
