"""Add user_id to OTP model

Revision ID: d27abe2b8ea5
Revises: 0e9564129d1d
Create Date: 2025-03-27 14:50:53.526844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd27abe2b8ea5'
down_revision = '0e9564129d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_column('otp', 'user_id')
    # ### end Alembic commands ###
