"""Add column  is_premium to User model

Revision ID: d85c9cd00dc5
Revises: c70614f4de10
Create Date: 2025-01-27 08:13:35.160566

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd85c9cd00dc5'
down_revision = 'c70614f4de10'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column with a default value of false for existing rows
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Remove the server default so future inserts require explicit values
    op.alter_column('user', 'is_premium', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###
