"""add_created_at_and_updated_at_to_user

Revision ID: e27eeb2053b0
Revises: 428436e2c7c8
Create Date: 2025-07-20 18:03:52.625377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = 'e27eeb2053b0'
down_revision = '428436e2c7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add columns as nullable
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Update existing records with current timestamp
    current_time = datetime.now(timezone.utc)
    op.execute(f"UPDATE \"user\" SET created_at = '{current_time}' WHERE created_at IS NULL")
    op.execute(f"UPDATE \"user\" SET updated_at = '{current_time}' WHERE updated_at IS NULL")
    
    # Now make the columns non-nullable
    op.alter_column('user', 'created_at', nullable=False)
    op.alter_column('user', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
