"""add_reset_password_token_table

Revision ID: e29e1eae0a90
Revises: ec9747f7afd7
Create Date: 2025-05-06 16:27:01.880356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e29e1eae0a90'
down_revision = 'ec9747f7afd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_password_token_application_id'), 'reset_password_token', ['application_id'], unique=False)
    op.create_index(op.f('ix_reset_password_token_email'), 'reset_password_token', ['email'], unique=False)
    op.create_index(op.f('ix_reset_password_token_user_id'), 'reset_password_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_password_token_user_id'), table_name='reset_password_token')
    op.drop_index(op.f('ix_reset_password_token_email'), table_name='reset_password_token')
    op.drop_index(op.f('ix_reset_password_token_application_id'), table_name='reset_password_token')
    op.drop_table('reset_password_token')
    # ### end Alembic commands ###
