"""add_application_id_to_feedback

Revision ID: f1a39e1ea8e6
Revises: c08ba4e14488
Create Date: 2025-04-21 11:54:35.542982

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a39e1ea8e6'
down_revision = 'c08ba4e14488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reset_password_token_application_id', table_name='reset_password_token')
    op.drop_index('ix_reset_password_token_email', table_name='reset_password_token')
    op.drop_index('ix_reset_password_token_user_id', table_name='reset_password_token')
    op.drop_table('reset_password_token')
    op.alter_column('application', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint('application_api_key_key', 'application', type_='unique')
    op.create_index(op.f('ix_application_name'), 'application', ['name'], unique=False)
    op.create_index(op.f('ix_application_package_name'), 'application', ['package_name'], unique=True)
    op.add_column('feedback', sa.Column('application_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_feedback_application_id'), 'feedback', ['application_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'application', ['application_id'], ['id'])
    op.create_index(op.f('ix_invitation_application_id'), 'invitation', ['application_id'], unique=False)
    op.create_index(op.f('ix_user_application_id'), 'user', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_application_id'), table_name='user')
    op.drop_index(op.f('ix_invitation_application_id'), table_name='invitation')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_application_id'), table_name='feedback')
    op.drop_column('feedback', 'application_id')
    op.drop_index(op.f('ix_application_package_name'), table_name='application')
    op.drop_index(op.f('ix_application_name'), table_name='application')
    op.create_unique_constraint('application_api_key_key', 'application', ['package_name'])
    op.alter_column('application', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('reset_password_token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name='resetpasswordtoken_application_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resetpasswordtoken_pkey')
    )
    op.create_index('ix_reset_password_token_user_id', 'reset_password_token', ['user_id'], unique=False)
    op.create_index('ix_reset_password_token_email', 'reset_password_token', ['email'], unique=False)
    op.create_index('ix_reset_password_token_application_id', 'reset_password_token', ['application_id'], unique=False)
    # ### end Alembic commands ###
